### ISSUE TITLE
no user agent specified

### ISSUE THREAD

**Issue by constructivetim** [codahale/passpol#2]
I am getting 403 back from https://api.pwnedpasswords.com/range/

I believe this is because https://haveibeenpwned.com/API/v2#UserAgent

**Comment by codahale** [comment]
Interesting: I can’t reproduce. `HttpURLConnection` sets a `User-Agent` itself, so I wonder if your specific version of Java has been blocked.

Can you try 976982a8f6884d87c66ac6cd44f9a64b6add7e42 and let me know if it works for you?

**Comment by codahale** [comment]
Released 0.5.1 with the fix.

**Comment by constructivetim** [comment]
this works now.

thanks very much.  

tim
